### ISSUE TITLE
Error in building packages 

### ISSUE THREAD

**Issue by Basil-3** [grpc-ecosystem/grpc-httpjson-transcoding#29]
After cloning, I ran bazel command to build project and I ran into following errors:
Starting local Bazel server and connecting to it...
ERROR: /home/basil/.cache/bazel/_bazel_basil/c7fbbb4ed84ea4e033d6d8801ef24b13/external/protobuf_git/BUILD:597:1: Traceback (most recent call last):
	File "/home/basil/.cache/bazel/_bazel_basil/c7fbbb4ed84ea4e033d6d8801ef24b13/external/protobuf_git/BUILD", line 597
		internal_gen_well_known_protos_java(srcs = WELL_KNOWN_PROTOS)
	File "/home/basil/.cache/bazel/_bazel_basil/c7fbbb4ed84ea4e033d6d8801ef24b13/external/protobuf_git/protobuf.bzl", line 266, in internal_gen_well_known_protos_java
		Label(("%s//protobuf_java" % REPOSITOR...))
	File "/home/basil/.cache/bazel/_bazel_basil/c7fbbb4ed84ea4e033d6d8801ef24b13/external/protobuf_git/protobuf.bzl", line 266, in Label
		REPOSITORY_NAME
builtin variable 'REPOSITORY_NAME' is referenced before assignment.
ERROR: /home/basil/.cache/bazel/_bazel_basil/c7fbbb4ed84ea4e033d6d8801ef24b13/external/protobuf_git/BUILD:101:1: Target '@protobuf_git//:windows' contains an error and its package is in error and referenced by '@protobuf_git//:protobuf'
ERROR: /home/basil/.cache/bazel/_bazel_basil/c7fbbb4ed84ea4e033d6d8801ef24b13/external/protobuf_git/BUILD:101:1: Target '@protobuf_git//:windows_msvc' contains an error and its package is in error and referenced by '@protobuf_git//:protobuf'
ERROR: /home/basil/.cache/bazel/_bazel_basil/c7fbbb4ed84ea4e033d6d8801ef24b13/external/protobuf_git/BUILD:101:1: Target '@protobuf_git//:android' contains an error and its package is in error and referenced by '@protobuf_git//:protobuf'
ERROR: /home/basil/.cache/bazel/_bazel_basil/c7fbbb4ed84ea4e033d6d8801ef24b13/external/protobuf_git/BUILD:101:1: Target '@protobuf_git//:windows' contains an error and its package is in error and referenced by '@protobuf_git//:protobuf'
ERROR: /home/basil/.cache/bazel/_bazel_basil/c7fbbb4ed84ea4e033d6d8801ef24b13/external/protobuf_git/BUILD:101:1: Target '@protobuf_git//:windows_msvc' contains an error and its package is in error and referenced by '@protobuf_git//:protobuf'
ERROR: /home/basil/Desktop/GSOC2019/grpc-httpjson-transcoding/repositories.bzl:47:9: Target '@protobuf_git//:protobuf' contains an error and its package is in error and referenced by '//external:protobuf'
ERROR: Analysis of target '//test:request_message_translator_test' failed; build aborted: Analysis failed
INFO: Elapsed time: 4.880s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (15 packages loaded, 87 targets configured)
    Fetching @com_google_absl; fetching
    Fetching @googleapis_git; fetching
    Fetching @googletest_git; fetching

**Comment by qiwzhang** [comment]
What bazel version are you using?

**Comment by Basil-3** [comment]
0.23.0

**Comment by qiwzhang** [comment]
https://github.com/grpc-ecosystem/grpc-httpjson-transcoding/pull/30

**Comment by Basil-3** [comment]
I updated both files and now I got this error:

bazel build //...

Starting local Bazel server and connecting to it...
INFO: Analysed 31 targets (29 packages loaded, 1195 targets configured).
INFO: Found 31 targets...
ERROR: /home/basil/.cache/bazel/_bazel_basil/c7fbbb4ed84ea4e033d6d8801ef24b13/external/protobuf_git/BUILD:120:1: C++ compilation of rule '@protobuf_git//:protobuf' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 ... (remaining 39 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
gcc: error: unrecognized command line option '-Wthread-safety'
gcc: error: unrecognized command line option '-Wself-assign'
gcc: error: unrecognized command line option '-fcolor-diagnostics'
INFO: Elapsed time: 68.367s, Critical Path: 0.95s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by Vedarth** [comment]
I am facing the same issue
